spring:
  datasource:
    url: jdbc:h2:tcp://localhost:1521/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100 #배치사이즈
        #show_sql: true #SQL ?? #???? ??
        format_sql: true #Formmatting

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace